## This docker-compose file is designed to be used as a template in portainer.
## It is widely (completely) inspired from the funkypenguin's cookbook.
## Don't miss his webpage: https://geek-cookbook.funkypenguin.co.nz
##
##
## This template can be set up in your portainer "App template".
## Don't forget to set the following environment variables:
## - PUID => user id that can read/write the media files.
## - PGID => group id that can read/write the media files.
## - DOMAIN => your DNS domainname ( example.com )
## - OAUTH2_PROXY_CLIENT_ID => please see https://github.com/bitly/oauth2_proxy
## - OAUTH2_PROXY_CLIENT_SECRET => please see https://github.com/bitly/oauth2_proxy
## - OAUTH2_PROXY_COOKIE_SECRET => Some random long string

version: "3.0"

services:
  plex:
    image: linuxserver/plex
    volumes:
      - /var/data/volumes/plex:/config
      - /media/gmedia:/media
      - /media/gmedia:/data
      - /media/gmedia:/media/GSuiteCrypt
    deploy:
      labels:
        - traefik.frontend.rule=Host:plex.$DOMAIN
        - traefik.docker.network=traefik_public
        - traefik.port=32400
    networks:
        - traefik_public
        - internal
    ports:
      - 32469:32469
      - 32400:32400
      - 32401:32401
      - 3005:3005
      - 8324:8324
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - VERSION=latest
      - EDGE=1
      - PUID=$PUID
      - PGID=$PGID
      - TZ=Europe/Paris
      - PLEX_MEDIA_SERVER_USE_SYSLOG=true

  tautulli:
    image: "linuxserver/tautulli:latest"
    volumes:
      - /var/data/volumes/tautulli:/config
    networks:
      - internal
    environment:
      - EDGE=1
      - PUID=$PUID
      - PGID=$PGID
      - TZ=Europe/Paris
      
  tautulli-proxy:
    image: a5huynh/oauth2_proxy
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:tautulli.$DOMAIN
        - traefik.docker.network=traefik_public
        - traefik.port=4180
    volumes:
      - /var/data/volumes/authenticated-emails.txt:/authenticated-emails.txt
    command: |
      -cookie-secure=false
      -upstream=http://tautulli:8181
      -redirect-url=https://tautulli.$DOMAIN
      -http-address=http://0.0.0.0:4180
      -email-domain=$DOMAIN
      -provider=google
      -authenticated-emails-file=/authenticated-emails.txt
    environment:
      - OAUTH2_PROXY_CLIENT_ID=$OAUTH2_PROXY_CLIENT_ID
      - OAUTH2_PROXY_CLIENT_SECRET=$OAUTH2_PROXY_CLIENT_SECRET
      - OAUTH2_PROXY_COOKIE_SECRET=$OAUTH2_PROXY_COOKIE_SECRET
      
networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.16.0/24
